[workspace]
members = [
    "crates/common",
    "crates/runtime",
    "crates/policy",
    "crates/validators",
    "crates/identity",
    "crates/router",
    "crates/hostcalls",
    "crates/loader",
    "crates/gateway",
]
resolver = "2"
