[package]
name = "logline_hostcalls"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
logline_common = { path = "../common" }
logline_runtime = { path = "../runtime" }
